### ISSUE TITLE
Memory Leak in C++

### ISSUE THREAD

**Issue by chilligerchief** [fidelity/seq2pat#16]
Hello,
the module does not free the memory it reserves. Deleting the `seq2pat` object in python does not change anything.
Running the following code will use up more and more memory as long as the loop runs. 

```from sequential.seq2pat import Seq2Pat, Attribute
for i in range(2000000):
    seq2pat = Seq2Pat(sequences=[["a","a","a"], ["a","b","c"],["a","b","b"],["a","a","a"], ["a","b","c"],["a","b","b"],["a","a","a"], ["a","b","c"],["a","b","b"]])
    traces = seq2pat.get_patterns(min_frequency=5)

**Comment by takojunior** [comment]
Thanks @chilligerchief for your interests to our library. This mentioned case and its memory usage haven't been tested. By using your test, we are able to observe it uses more and more memory as long as loop runs. We will look into this and have a fix accordingly.

**Comment by chilligerchief** [comment]
Thank you for looking into it. For now I use a hacky fix by calling an external script. Once the process is finished, the memory gets freed. Sadly, I am not comfortable enough in C++ to fix it my own.

**Comment by skadio** [comment]
In the most recent version/fix, we made a few improvements in the C++ backend with more explicit memory clean-up. This may or may not help with your specific case. More memory improvements might be possible in the future. This is our best effort in the short term. I liked your suggestion of running it within external script to keep the memory alloc in control —great fix! Thank you again for sharing your feedback
