### ISSUE TITLE
[Question] - Sequence of transaction basket

### ISSUE THREAD

**Issue by galimba39** [fidelity/seq2pat#29]
Hi,

thank you for your work.
Is your software able to handle sequence formed like the one below?

    seq2pat = Seq2Pat(sequences=[ [["A1", "A2", "B"], ["A", "D"]],`
                                  [["C", "B"], ["A"]],`
                                  [["C", "A"], ["C", "D"]]])`

So, for instance, the first sequence is a tuple of 3 elements - A1,A2,B - followed by a couple of 2 elements - A,D.

**Comment by skadio** [comment]
The short answer is no, the software is independent of the definition of an _item_. 

If the _item_ of interest is a tuple as in <A1,A2,B>, then you can transform the data to map them, say to X. Likewise, <A,D> to represent another item Y. Then, the event sequence of tuples [["A1", "A2", "B"], ["A", "D"]] becomes [X, Y]. 

In essence, what we call "items" does not really matter (it can be single items, or tuples) and is not an off-the-shelf transformation within the library, we leave that definition to the specific application.

**Comment by galimba39** [comment]
Actually I was interested in investigating the relation within each single tuple element, such as A1 -> D but I think this is not the expected usage.
Thank you for your answer and your work!

**Comment by skadio** [comment]
I see, makes sense. If there is a sequence relationship "within" the tuple, may be it is not a static tuple then? As in, items should remain as A1, A2, B and the sequence becomes A1 -> A2 -> B whereby you would have "two" sequences in your first row in the example [["A1", "A2", "B"], ["A", "D"]]  --> ["A1", "A2", "B"] as one sequence and ["A", "D"] as another sequence. Just an idea. 

Thanks for the positive feedback!

**Comment by galimba39** [comment]
I guess yes, tuple size is definitely not static. 
My question was trying to address whether this algorithm was fitting the use case of PrefixSpan, such as, in this case

`["A1", "A2", "B"], ["A", "D"]`

evaluating independently single element A1, A2 and B implying A or D and eventually subsets of tuples, e.g. {A1,A2} -> {A}
I attached here this [video](https://www.youtube.com/watch?v=7QIUv3dRSIE&ab_channel=PhilippeFournier-Viger) to explain better the scenario.

**Comment by skadio** [comment]
Great video -- thank you for sharing! 

The short answer is no, not out of the box, since the library consider sequences with singleton items (as opposed to a tuple like (A1, A2, B) being an item). 

Some data transformation might be possible during pre-processing to feed the input accordingly, OR, dropping the tuples to check if, in your example, A1, A2, A still shows up as frequent at the end. 

That said, under the hood for the MDD propagation, there are great parallels with the PrefixSpan algorithm like the pseudo-projection etc.
