### ISSUE TITLE
data still available to download?

### ISSUE THREAD

**Issue by Sandy4321** [fidelity/seq2pat#31]
is data set from 
Seq2Pat: Sequence-to-Pattern Generation
for Constraint-Based Sequential Pattern Mining

still available to download
if yes
what is the link ?
Clickstream Data The dataset contains rich clickstream
behavior on online users browsing a popular fashion ecommerce website (Requena et al. 2020).

**Comment by Sandy4321** [comment]
is it 
https://www.coveo.com/en/ailabs/shopper-intent-prediction-from-clickstream-e-commerce-data-with-minimal-browsing-information

https://github.com/coveooss/shopper-intent-prediction-nature-2020

**Comment by skadio** [comment]
This is correct. 

We kindly request that you follow the Data Privacy rules from the original providers and to cite their paper if this data is used. You can of course cite/star Seq2Pat too, if it is relevant/used.

**Comment by Sandy4321** [comment]
can you have to get data
since provided web link for data is broken
downloading is not started for hours
![image](https://user-images.githubusercontent.com/11426119/227792716-d267ede6-e53d-4b85-aab2-68f4a0d194e4.png)

**Comment by skadio** [comment]
We do not own this dataset, plz check with the original authors.

**Comment by canerturkseven** [comment]
@Sandy4321 Hi Sandy, did you find a way to get the dataset?

**Comment by Sandy4321** [comment]
no
