### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by sajjadriaj** [fidelity/seq2pat#32]
Hi, I am getting the following error while trying to install the package: 

>  LINK : fatal error LNK1158: cannot run 'rc.exe'
  C:\Users\..\AppData\Local\Temp\pip-build-env-0ce14mib\overlay\Lib\site-packages\setuptools\command\build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'sequential.backend' as data is deprecated, please list it in `packages`.
      !!

      ############################
      # Package would be ignored #
      ############################
      Python recognizes 'sequential.backend' as an importable package,
      but it is not listed in the `packages` configuration of setuptools.

      'sequential.backend' has been automatically added to the distribution only
      because it may contain data files, but this behavior is likely to change
      in future versions of setuptools (and therefore is considered deprecated).

      Please make sure that 'sequential.backend' is included as a package by using
      the `packages` configuration field or the proper discovery methods
      (for example by using `find_namespace_packages(...)`/`find_namespace:`
      instead of `find_packages(...)`/`find:`).

      You can read more about "package discovery" and "data files" on setuptools
      documentation page.
    check.warn(importable)
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit code 1158
  ERROR: Failed building wheel for seq2pat
Failed to build seq2pat
ERROR: Could not build wheels for seq2pat which use PEP 517 and cannot be installed directly

**Comment by takojunior** [comment]
@sajjadriaj Thanks for your interests! Could you share more information of your Python environment? The current release has been tested on Python 3.6 - 3.10 on the latest windows os with Visual Studio 2022 installed. So knowing more about your environment would be helpful to identify the issue.

**Comment by takojunior** [comment]
Closing this issue, but let us know if you still can not install now @sajjadriaj
