### ISSUE TITLE
Integer sequences containing zero (0) as an event

### ISSUE THREAD

**Issue by victorjmarin** [fidelity/seq2pat#33]
Firstly, thank you for sharing your work.

I found out that using `0` as an event in a sequence of integers is problematic. The output may be incorrect (empty) or a segmentation fault may occur.

```
from sequential.seq2pat import Seq2Pat

# "0" as a string works well
seq2pat = Seq2Pat(sequences=[['0', '0'], ['0', '0']])
patterns = seq2pat.get_patterns(min_frequency=2)
print(patterns)  # Outputs [['0', '0', 2]]

# No error but incorrect output
seq2pat = Seq2Pat(sequences=[[1, 0], [1, 0]])
patterns = seq2pat.get_patterns(min_frequency=2)
print(patterns)  # Outputs []. Expecting [[1, 0, 2]].

# Produces a segmentation fault
seq2pat = Seq2Pat(sequences=[[0, 0], [0, 0]])
patterns = seq2pat.get_patterns(min_frequency=2)
print(patterns)
```
It could be helpful to document this issue in the [README.md](https://github.com/fidelity/seq2pat/blob/master/README.md) until a fix can be produced either by fixing the underlying cause, converting sequences to strings, or preprocessing integer sequences to rename `0` events.

**Comment by skadio** [comment]
Thank you for raising this special! Let us look into it in the next few weeks and we will circle back

**Comment by skadio** [comment]
@takojunior for awareness

**Comment by takojunior** [comment]
Thanks @victorjmarin. We are able to reproduce the issue. 

By checking the implementation of the mining process, we find that we need to ensure the input integers are positive integers. `0` may cause undefined behaviors. We would plan to include this fix in input validation in next release, and update documentations accordingly.
