### ISSUE TITLE
Request for metadata on the event_time column

### ISSUE THREAD

**Issue by dinaamir** [fidelity/seq2pat#44]
Hi there!

Thank you for the amazing library and for sharing it openly!

I gave it a try on running cell-by-cell code from the dichotomic_pattern_mining.ipynb file using the same dataset from Requena (2020). By referring to the sample_data.csv used in the mentioned .ipynb file, do you mind elaborate more on the metadata of the column `event_time`, for example, the unit (is it in seconds, milliseconds, or in other form?). 

You also mentioned that the `event_time` column (as well as the other columns) is extracted from the original dataset. I am assuming that the `event_time` column is constructed from the column `server_timestamp_epoch_ms` which we can also get from the original dataset. If so, do you mind sharing how the process of constructing the `event_time` was done? 

Looking forward to hear from you. Thanks!

**Comment by takojunior** [comment]
Thanks @dinaamir for your interests to the library! 

The `event_time` is in milliseconds. So it shows the time that a user spent on each visit in `event_sequence`, mostly a few tens of seconds.

We extracted `event_time` by calculating the time elapsed in the consecutive timestamps, e.g. event_time_1 = timestamp_2 - timestamp_1. The last event time in a sequence can't be estimated in this way, so we used median of the preceding event times in that sequence.
