### ISSUE TITLE
Performance warning when using pat2feat.get_features

### ISSUE THREAD

**Issue by jcklie** [fidelity/seq2pat#47]
Thank you for this wonderful library, it works really well so far. When using `pat2feat.get_features` to extract features for many patterns, then I get lots of 

```
/sequential/pat2feat.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['feature_' + str(i)] = df.apply(lambda row: is_satisfiable_in_rolling(row['sequence'], pattern,
```

Would it be possible to generate the column data first and then bulk create the dataframe by concatenating, instead of adding them to the dataframe 1 by 1? Would it also be possible to directly return a numpy array by pat2feat, as pandas is often an overkill?

```
#Sequences: 108
#Patterns: 4300

pandas==2.0.2
seq2pat==1.4.0
```

**Comment by skadio** [comment]
Closing for now to revisit later on.
