### ISSUE TITLE
Inquiry on performance-improvement in context of small number of long sequences

### ISSUE THREAD

**Issue by jgwak1** [fidelity/seq2pat#51]
Thank you for the great repository!

Seq2Pat Experimental/Results summary indicates that the "batch_size" parameter can lead to performance improvement for a large number of sequences (e.g., 100k to 1M).
[seq2pat experimental/results summary](https://github.com/fidelity/seq2pat/blob/1b27c79af4c5d33c8714b9f010dd8ea4efd26d50/sequential/seq2pat.py#L330)

However, in context of smaller number of data points (hundreds or thousands) but long sequences (30,000 to 50,000 length), my guess is "batch_size" may not be as helpful. 

In this case, would increasing the "n_jobs" parameter be beneficial?

**Comment by skadio** [comment]
My intuition matches your comment; for small data points batch_size might not be of immediate interest. @takojunior  can confirm.

Likewise, n_jobs is to parallelize the batches, so it might be beneficial either. 

Check out to the max-span constraint, and the default max-span=10 in the seq2pat() constructor. That's more relevant for long sequences. You might want to reduce that sth even smaller for extreme lenghts

Btw, thanks for the positive comment. Please consider a GitHub star, if not already 🌟
