### ISSUE TITLE
Span constraint is imposed by default

### ISSUE THREAD

**Issue by aminhn** [fidelity/seq2pat#54]
The code seems to be imposing a span constrain 1 < span < 9 by default. 
I had to mannually remove it by running seq2pat.attr_to_cts.clear().
This default constraint is not mentioned in the ReadMe, and leads to incorrect results if not paid attention to.
This should be either removed or clearly mentioned in the ReadMe.
Thanks!

**Comment by aminhn** [comment]
Perfect, thank you!


Amin Hosseininasab
Assistant Professor of Marketing
Department of Marketing
Warrington College of Business
University of Florida
https://warrington.ufl.edu/directory/person/12519/<https://warrington.ufl.edu/directory/person/12519/>
________________________________

**Comment by skadio** [comment]
New section "Mining Large Sequence Databases" added to Readme now --will be available in next merge

https://github.com/fidelity/seq2pat/tree/ci-fix?tab=readme-ov-file#mining-large-sequence-databases
